env: {}

log:
  loglevel: warning

dns:
  servers:
    - address: "https+local://223.5.5.5/dns-query"
      domains: &direct_domains
        - "domain:example.com"
      skipFallback: true
      finalQuery: true

    - address: "https://1.1.1.1/dns-query"
      domains: &proxy_domains
        - "geosite:category-dev"
        - "geosite:google"
        - "geosite:nodeseek"
        - "geosite:openai"
      skipFallback: true

    - address: "https://8.8.8.8/dns-query"
      domains: *proxy_domains
      skipFallback: true
      finalQuery: true

    - address: "https+local://223.5.5.5/dns-query"
      domains:
        - "geosite:cn"
      expectedIPs:
        - "geoip:cn"
      skipFallback: true

    - address: "https://1.1.1.1/dns-query"

    - address: "https://8.8.8.8/dns-query"

  tag: "dns-server"
  queryStrategy: UseSystem

routing:
  domainStrategy: IPOnDemand
  rules:
    - type: field
      port: 53
      outboundTag: dns-hanlder

    - type: field
      inboundTag:
        - dns-server
      outboundTag: proxy-out

    - type: field
      protocol:
        - bittorrent
      outboundTag: direct-out

    - type: field
      port: "443"
      network: udp
      outboundTag: block

    - type: field
      domain:
        - "geosite:private"
      outboundTag: direct-out

    - type: field
      ip:
        - "geoip:private"
      outboundTag: direct-out

    - type: field
      ip:
        - "geoip:cn"
      outboundTag: direct-out

    - type: field
      domain: *direct_domains
      outboundTag: direct-out

    - type: field
      domain: *proxy_domains
      outboundTag: proxy-out

policy: {}

inbounds:
  - tag: default-in
    port: 12345
    protocol: tunnel
    settings:
      allowedNetwork: "tcp,udp"
      followRedirect: true
    streamSettings:
      sockopt:
        tproxy: tproxy
    sniffing:
      enabled: true
      destOverride:
        - http
        - tls
        - quic

outbounds:
  - tag: direct-out
    protocol: freedom
    settings:
      domainStrategy: ForceIP

  - tag: proxy-out
    protocol: vless
    settings:
      address: example.com
      port: 443
      id: 00000000-0000-0000-0000-000000000000
      encryption: none
    streamSettings:
      network: xhttp
      security: tls
      tlsSettings:
        allowInsecure: false
        alpn:
          - h2
      xhttpSettings:
        path: /liveStream
        mode: stream-one

  - tag: dns-hanlder
    protocol: dns
    settings:
      rules:
        - action: hijack

  - tag: block
    protocol: blackhole

  - tag: block-ads
    protocol: blackhole
