x-vars:
  node_domains: &node_domains
    - "domain:example.com"

  proxy_domains: &proxy_domains
    - "domain:github.com"

  proxy_ips: &proxy_ips
    - "1.1.1.1"

  proxy_address: &proxy_address "example.com"

log:
  loglevel: warning

dns:
  hosts:
    "geosite:category-ads-all": "#3"

  servers:
    - address: "https+local://223.5.5.5/dns-query"
      domains: *node_domains
      skipFallback: true
      finalQuery: true

    - address: "https://1.1.1.1/dns-query"
      domains: *proxy_domains
      skipFallback: true

    - address: "https://8.8.8.8/dns-query"
      domains: *proxy_domains
      skipFallback: true
      finalQuery: true

    - address: "https+local://223.5.5.5/dns-query"
      domains:
        - "geosite:cn"
      expectedIPs:
        - "geoip:cn"
      skipFallback: true

    - address: "https://1.1.1.1/dns-query"

    - address: "https://8.8.8.8/dns-query"

  queryStrategy: UseSystem
  tag: "dns-in"

routing:
  domainStrategy: AsIs
  rules:
    - type: field
      port: 53
      outboundTag: dns-handler

    - type: field
      inboundTag:
        - dns-in
      outboundTag: proxy-out

    - type: field
      protocol:
        - bittorrent
      outboundTag: direct-out

    - type: field
      port: "443"
      network: udp
      outboundTag: block

    - type: field
      domain: *proxy_domains
      outboundTag: proxy-out

    - type: field
      ip: *proxy_ips
      outboundTag: proxy-out

inbounds:
  - tag: tunnel-in
    port: 12345
    protocol: tunnel
    settings:
      network: "tcp,udp"
      followRedirect: true
    streamSettings:
      sockopt:
        tproxy: tproxy
    sniffing:
      enabled: true
      destOverride:
        - http
        - tls
      routeOnly: true

outbounds:
  - tag: direct-out
    protocol: freedom

  - tag: proxy-out
    protocol: vless
    settings:
      address: *proxy_address
      port: 443
      id: "00000000-0000-0000-0000-000000000000"
      encryption: none
    streamSettings:
      network: xhttp
      security: tls
      tlsSettings:
        allowInsecure: false
        alpn:
          - h2
      xhttpSettings:
        path: /path
        mode: stream-one
      sockopt:
        domainStrategy: UseIP

  - tag: dns-handler
    protocol: dns
    settings:
      rules:
        - action: hijack

  - tag: block
    protocol: blackhole

  - tag: block-ads
    protocol: blackhole
