#!/bin/sh

NFT=/usr/sbin/nft
[ -x "$NFT" ] || NFT=/usr/bin/nft

if [ "${NFTFLOW_NFT_TERSE:-0}" = "1" ] && [ "$1" = "list" ] && [ "$2" = "table" ]; then
    exec "$NFT" --terse "$@"
fi

exec "$NFT" "$@"
